site_name: That's Me
site_url: https://onplastic.github.io/Portfolio/
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Über mich: index.md
  - Dokumentation: documentation.md
  - Kontakt: contact.md
  - Impressum: impressum.md
  - Datenschutzerklärung: datenschutzerklaerung.md
plugins:
  - search

markdown_extensions:
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - admonition
  - toc: 
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          -overrides/.icons
extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Einstellungen
    description: >-
      Diese Website verwendet Cookies, um sicherzustellen, dass Sie die beste Erfahrung auf dieser Website erhalten. Durch die Nutzung der Website stimmen Sie der Verwendung von Cookies zu. Für mehr Informationen besuchen Sie die <a href="/Portfolio/datenschutzerklaerung/">Datenschutzerklärung</a> dieser Site.
  generator: false
  social:
    - icon: simple/mastodon
      link: https://mastodon.social/@OnPlastic
      name: OnPlastic @Mastodon
    - icon: octicons/mail-16
      link: mailto:<dope.on.plastic@web.de>
    - icon: fontawesome/brands/github
      link: https://github.com/OnPlastic/Portfolio
      name: OnPlastic @GitHub
copyright: Copyright &copy; 2024 On Plastic | <a href="#__consent">Cookie Settings</a> | <a href="/Portfolio/impressum">Impressum</a> | <a href="/Portfolio/datenschutzerklaerung">Datenschutzerklärung</a>
repo_url: https://github.com/OnPlastic/Portfolio
repo_name: GitHub/Portfolio
extra_css:
  - css/extra.css
  - stylesheets/extra.css
  
